DROP DATABASE IF EXISTS miyazaki;
CREATE DATABASE miyazaki CHARACTER SET 'utf8';
USE miyazaki;

CREATE USER IF NOT EXISTS 'octave'@'localhost' IDENTIFIED BY 'evatco';
GRANT ALL PRIVILEGES ON miyazaki .*  TO 'octave'@'localhost';

CREATE TABLE films (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(40) NOT NULL UNIQUE,
  annee SMALLINT,
  note VARCHAR(255),
  image VARCHAR(255)
) ENGINE=InnoDB;

CREATE TABLE heros (
  id SMALLINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  nom VARCHAR(40) NOT NULL UNIQUE,
  id_film TINYINT UNSIGNED NOT NULL,
  description VARCHAR(255),
  role VARCHAR(40),
  FOREIGN KEY (id_film) REFERENCES films(id)
) ENGINE=InnoDB;

CREATE TABLE genre (
  id TINYINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  genre VARCHAR(40) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE jonction (
  id_film TINYINT UNSIGNED NOT NULL,
  id_genre TINYINT UNSIGNED NOT NULL,
  FOREIGN KEY (id_film) REFERENCES films(id),
  FOREIGN KEY (id_genre) REFERENCES genre(id),
  PRIMARY KEY (id_film, id_genre)
) ENGINE=InnoDB;
